# Generated by Django 4.2.8 on 2024-02-26 06:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='bannertop')),
                ('rating', models.FloatField(default='')),
                ('link', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, max_length=30, null=True)),
                ('product', models.IntegerField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, null=True)),
                ('poster', models.ImageField(upload_to='product_image')),
                ('description', ckeditor.fields.RichTextField()),
                ('release_date', models.CharField(default='', max_length=20)),
                ('actors', models.TextField(blank=True, null=True)),
                ('youtube', models.CharField(default='', max_length=250, null=True)),
                ('download', models.CharField(default='', max_length=250, null=True)),
                ('tags', models.CharField(default='', max_length=250, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=555, null=True, unique=True)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True)),
                ('creator', models.IntegerField(blank=True, max_length=30, null=True)),
                ('categories', models.ManyToManyField(to='Home.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('prod_parent', models.IntegerField(default='', max_length=100)),
                ('review', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('reply', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('review_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.review')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=250)),
                ('rating', models.IntegerField()),
                ('prod_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Additional_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.product')),
            ],
        ),
    ]
